version: '3.5'
services:
  smartlibrary_operations:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./smartlibrary_operations:/smartlibrary_operations
    mem_limit: 8000Mb
    depends_on:
      - "fragrances_database"
    environment:
      PYTHONPATH: .
      FRAGRANCEDB_HOST: fragrances_database
      FRAGRANCEDB_NAME: fragrancedb
      FRAGRANCEDB_USERNAME: scentmate_user
      FRAGRANCEDB_PASSWORD: scentmate_password
      FRAGRANCEDB_PORT: 5432
      FRAGRANCEDB_EXTRA: "?"
      ENVIRONMENT: dev
  #    oom_kill_disable: true
  fragrances_database:
    container_name: test_database
    image: postgres:11
    ports:
      - '25432:5432'
    volumes:
      - ./tests/data/elx-e2e-and-unit-test-db.sql:/docker-entrypoint-initdb.d/1-fragrances.sql
    environment:
      POSTGRES_USER: scentmate_user
      POSTGRES_PASSWORD: scentmate_password
      POSTGRES_DB: fragrancedb
