# Generated by Django 4.0.4 on 2022-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('address', models.CharField(max_length=600)),
                ('sqft_m2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('floor_elevator', models.IntegerField()),
                ('realestate', models.CharField(max_length=600)),
                ('realestate_id', models.BigIntegerField()),
                ('is_new_construction', models.BooleanField()),
                ('conservation_state', models.BooleanField()),
                ('building_type', models.CharField(max_length=200)),
                ('building_subtype', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('neighbourhood', models.CharField(max_length=200)),
                ('neighbourhood_id', models.IntegerField()),
                ('neighbourhood_meanprice', models.DecimalField(decimal_places=10, max_digits=19)),
                ('neighbourhood_meanprice_difference', models.DecimalField(decimal_places=10, max_digits=19)),
                ('price_m2', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
