# Generated by Django 4.0.4 on 2022-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_flatinfo_conservation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatinfo',
            name='conservation_state',
            field=models.IntegerField(null=True),
        ),
    ]
