# Generated by Django 4.0.4 on 2022-05-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_flatinfo_conservation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NeighbourhoodMeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('sqft_m2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rooms', models.DecimalField(decimal_places=10, max_digits=19)),
                ('bathrooms', models.DecimalField(decimal_places=10, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('neighbourhood', models.CharField(max_length=200)),
                ('neighbourhood_id', models.IntegerField()),
                ('neighbourhood_meanprice_difference', models.DecimalField(decimal_places=10, max_digits=19)),
                ('price_m2', models.DecimalField(decimal_places=10, max_digits=19)),
                ('extract_info_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.extractioninfo')),
            ],
        ),
        migrations.AddField(
            model_name='flatinfo',
            name='extract_info_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.extractioninfo'),
        ),
    ]
