fotocasa_gencat_map = {
    "barri gòtic": "el barri gòtic",
    "el raval": "el raval",
    "la barceloneta": "la barceloneta",
    "sant pere, sta. caterina i la ribera" : "sant pere, santa caterina i la ribera",
    "dreta de l'eixample": "la dreta de l'eixample",
    "fort pienc": "el fort pienc",
    "la nova esquerra de l'eixample": "la nova esquerra de l'eixample",
    "l'antiga esquerra de l'eixample": "l'antiga esquerra de l'eixample",
    "sagrada familia": "la sagrada failia",
    "sant antoni": "sant antoni",
    "el camp d'en grassot i gràcia nova": "el camp d'en grassot i gràcia nova",
    "el coll": "el coll",
    "la salut": "la salut",
    "vallcarca i els penitents": "vallcarca i els penitents",
    "vila de gràcia": "la vila de gràcia",
    "can baró": "can baró",
    "el baix guinardó": "el baix guinardó",
    "el carmel": "el carmel",
    "el guinardó": "el guinardó",
    "horta": "horta",
    "la font d'en fargues": "la font d'en fargues",
    "la teixonera": "la teixonera",
    "la vall d'hebron": "la vall d'hebron",
    "montbau": "montbau",
    "sant genís dels agudells": "sant genís dels agudells",
    "barri de les corts": "les corts",
    "la maternitat i sant ramon": "la maternitat i sant ramon",
    "pedralbes": "pedralbes",
    "can peguera": "can peguera",
    "canyelles": "canyelles",
    "ciutat meridiana": "ciutat meridiana",
    "el turó de la peira": "el turó de la peira",
    "la guineueta": "la guineueta",
    "la prosperitat": "la prosperitat",
    "la trinitat nova": "la trinitat nova",
    "les roquestes": "les roquetes",
    "porta": "porta",
    "torre baró": "torre baró",
    "vallbona": "vallbona",
    "verdum": "verdun",
    "vilapicina i la torre llobeta": "vilapicina i la torre llobeta",
    "el bon pastor": "el bon pastor",
    "el congrés i els indians": "el congrés i els indians",
    "la sagrera": "la sagrera",
    "navas": "navas",
    "sant andreu del palomar": "sant andreu",
    "trinitat vella": "la trinitat vella",
    "diagonal mar i el front marítim del poblenou": "diagonal mar i el front marítim del poblenou",
    "el besós i el maresme": "el besòs i el maresme",
    "el camp de l'arpa del clot": "el camp de l'arpa del clot",
    "el clot": "el clot",
    "el parc i la llacuna del poblenou": "el parc i la llacuna del poblenou",
    "el poblenou": "el poblenou",
    "la verneda i la pau": "la verneda i la pau",
    "la vila olímpica del poblenou": "la vila olímpica del poblenou",
    "provençals del poblenou": "provençals del poblenou",
    "sant martí de provençals": "sant martí de provençals",
    "el poble sec - parc de montjuïc": "el poble sec - aei parc montjuïc",
    "hostafrancs": "hostafrancs",
    "la bordeta": "la bordeta",
    "la font de la guatlla": "la font de la guatlla",
    "la marina del port": "la marina del port",
    "sants": "sants",
    "sants-badal": "sants - badal",
    "zona franca - port": "",
    "el putget i el farró": "el putxet i el farró",
    "les tres torres": "les tres torres",
    "sant gervasi- galvany": "sant gervasi - galvany",
    "sant gervasi i la bonanova": "sant gervasi - la nonanova",
    "sarrià": "sarrià",
    "vallvidrera - tibidabo - les planes": "vallvidrera, el tibidabo i les planes"
}